version: 2.1 

commands:
    s3_web_deploy:
        description: 'Command for s3 web deploy'
        parameters:
            environment:
                type: string
                default: ''
            s3_bucketname:
                type: string
                default: ''
            AWS_ACCESS_KEY_ID:
                type: string
                default: ''
            AWS_SECRET_ACCESS_KEY:
                type: string
                default: ''
        steps:
            - run:
                  name: Install  dependencies
                  command: | 
                      npm install
            - run:
                  name: Install AWS CLI
                  command: |
                      sudo apt-get update && apt-get install -y python-dev
                      curl -O https://bootstrap.pypa.io/get-pip.py
                      sudo python get-pip.py
                      sudo pip install awscli --upgrade  
                      aws --version
                     
   
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers-legacy
        working_directory: ~/fww-web
        steps:
            - checkout
            - run: echo "Welcome"
            - run:
                  name: Install Serverless CLI and  dependencies
                  command: |
                     sudo apt-get update && apt-get install -y python3
                     curl -O https://bootstrap.pypa.io/get-pip.py
                     python3 get-pip.py --user
                     pip3 install awscli --upgrade --user  
                     aws --version

                  
workflows:
    version: 2
    build_accept_deploy:
        jobs:
            - build
