version: 2.1 

commands:
    s3_web_deploy:
        description: 'Command for s3 web deploy'
        parameters:
            environment:
                type: string
                default: ''
            s3_bucketname:
                type: string
                default: ''
            AWS_ACCESS_KEY_ID:
                type: string
                default: ''
            AWS_SECRET_ACCESS_KEY:
                type: string
                default: ''
        steps:
            - run:
                  name: Install  dependencies
                  command: |
                      npm install
            - run:
                  name: Install AWS CLI
                  command: |
                      sudo apt-get update && sudo apt-get install -y python-dev
                      curl -O https://bootstrap.pypa.io/get-pip.py
                      sudo python get-pip.py
                      sudo pip install awscli --upgrade  
                      aws --version
                     
   
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers-legacy
        working_directory: ~/fww-web
        steps:
            - checkout
            - run: echo "Welcome"
            - run:
                  name: Install Serverless CLI and  dependencies
                  command: |
                      npm install
           # - run:
           #       name: Running linting and prettier checks
           #       command: |
           #           #npm run lint && echo "++Linting Completed++"            
           #          # npm run prettier && echo "++Pretier run completed"
           #
            - run:
                name: Setup Code Climate test-reporter
                command: |
                        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                        chmod +x ./cc-test-reporter                    
           
            - store_test_results:
                  path: ./coverage

            - store_artifacts:
                  path: ./coverage

                  
workflows:
    version: 2
    build_accept_deploy:
        jobs:
            - build
            - s3_web_deploy
